In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.10.0'

In [8]:
dataset = pd.read_excel('C:/Course 2/Folds5x2_pp.xlsx')
dataset.head(10)

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90
5  26.27  59.44  1012.23  58.77  443.67
6  15.89  43.96  1014.02  75.24  467.35
7   9.48  44.71  1019.12  66.43  478.42
8  14.64  45.00  1021.78  41.25  475.98
9  11.74  43.56  1015.14  70.72  477.50

In [9]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:, -1].values
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
X_train

array([[  11.22,   43.13, 1017.24,   80.9 ],
       [  13.67,   54.3 , 1015.92,   75.42],
       [  32.84,   77.95, 1014.68,   45.8 ],
       ...,
       [  16.81,   38.52, 1018.26,   75.21],
       [  12.8 ,   41.16, 1022.43,   86.19],
       [  32.32,   67.9 , 1006.08,   37.93]])

In [13]:
ann = tf.keras.models.Sequential()

In [14]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

In [18]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

In [21]:
ann.add(tf.keras.layers.Dense(units = 1))

In [22]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

In [24]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 1s 3ms/step - loss: 185393.0000
Epoch 2/100
240/240 [==============================] - 1s 3ms/step - loss: 185187.1250
Epoch 3/100
240/240 [==============================] - 1s 3ms/step - loss: 184981.2656
Epoch 4/100
240/240 [==============================] - 1s 3ms/step - loss: 184775.4531
Epoch 5/100
240/240 [==============================] - 1s 3ms/step - loss: 184569.8750
Epoch 6/100
240/240 [==============================] - 1s 3ms/step - loss: 184364.3281
Epoch 7/100
240/240 [==============================] - 1s 3ms/step - loss: 184158.9844
Epoch 8/100
240/240 [==============================] - 1s 3ms/step - loss: 183953.5781
Epoch 9/100
240/240 [==============================] - 1s 3ms/step - loss: 183748.5000
Epoch 10/100
240/240 [==============================] - 1s 3ms/step - loss: 183543.4531
Epoch 11/100
240/240 [==============================] - 1s 3ms/step - loss: 183338.4531
Epoch 12/100
240/240 [===================

In [26]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision = 2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)), 1))

60/60 [==============================] - 0s 3ms/step
[[ 47.89 431.23]
 [ 47.89 460.01]
 [ 47.89 461.14]
 ...
 [ 47.89 473.26]
 [ 47.89 438.  ]
 [ 47.89 463.28]]
