In [4]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [5]:
tf.__version__

'2.10.0'

In [7]:
dataset = pd.read_csv("C:\Course 2\Python\Churn_Modelling.csv")
dataset.head(10)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   
5          6    15574012       Chu          645     Spain    Male   44   
6          7    15592531  Bartlett          822    France    Male   50   
7          8    15656148    Obinna          376   Germany  Female   29   
8          9    15792365        He          501    France    Male   44   
9         10    15592389        H?          684    France    Male   27   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   
6       7       0.00              2          1               1   
7       4  115046.74              4          1               0   
8       4  142051.07              2          0               1   
9       2  134603.88              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1  
6         10062.80       0  
7        119346.88       1  
8         74940.50       0  
9         71725.73       0

In [11]:
X = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [14]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [15]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [17]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [18]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 0)

In [19]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [20]:
ann = tf.keras.models.Sequential()

In [21]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

In [22]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

In [23]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

In [24]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [25]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6183 - accuracy: 0.7078
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4994 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4568 - accuracy: 0.7981
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4351 - accuracy: 0.8087
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4255 - accuracy: 0.8144
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4190 - accuracy: 0.8165
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4133 - accuracy: 0.8210
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4069 - accuracy: 0.8245
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4005 - accuracy: 0.8290
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3934 - accura

250/250 [==============================] - 0s 2ms/step - loss: 0.3313 - accuracy: 0.8621
Epoch 82/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3319 - accuracy: 0.8626
Epoch 83/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3313 - accuracy: 0.8634
Epoch 84/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3314 - accuracy: 0.8630
Epoch 85/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3310 - accuracy: 0.8637
Epoch 86/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3315 - accuracy: 0.8622
Epoch 87/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3310 - accuracy: 0.8612
Epoch 88/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3311 - accuracy: 0.8630
Epoch 89/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3311 - accuracy: 0.8624
Epoch 90/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3310 - accuracy: 

In [32]:
print(ann.predict(sc.transform(([[1,0,0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))>0.5))

1/1 [==============================] - 0s 19ms/step
[[0.09023303]]


In [33]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [35]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1530   65]
 [ 210  195]]


0.8625